### ISSUE TITLE
Project stability

### ISSUE THREAD

**Issue by tiagonovo0** [larics/frontier_exploration_3d#1]
Hello, I am a master's student of automation and robotics and I am doing a research on multi-robot 3D exploration. This project really cough my interest towards performing exploration based on frontiers. I would like to know how far along is the project and the state of it, that is, if it is stable to run and get good results from it. 

I cloned the repository from the branch frontier_devel, but it resulted in error when compiling the library <octomap/OcTreeLUT.h>. 

![Screenshot from 2020-04-17 00-45-23](https://user-images.githubusercontent.com/61195838/79517195-62636000-8045-11ea-8d85-866945ae7db5.png)

**Comment by AnaBatinovic** [comment]
Hi @tiagonovo0, thanks for your interest. 
This project is under active development. I took an idea from  [fbet](https://github.com/zcdoyle/fbet) repository. They have everything ready to use and test. 
My plan is to extend the fuctionality and make it suitable for our firmware. 

Regarding the error, I added some notes in installation instructions. You need to download an older version of the octomap ([issue](https://github.com/zcdoyle/fbet/issues/1) is already solved).
